Description: >
     This cloudfomation script will create and configure an ec2 instances and run jenkins inside it.

Parameters:
   InstanceType:
      Description: 'WebServer EC2 instance type'
      Type: 'String'
      Default: 't2.small'
      ConstraintDescription: 'must be a valid EC2 instance type.'

Resources:
   Ec2Instances:
      Type: "AWS::EC2::Instance"
      Properties:
        ImageId: "ami-050bc013"
        KeyName: "techgig"
        InstanceType: !Ref InstanceType
        AvailabilityZone: "us-east-1a"
        SecurityGroupIds: [!GetAtt SSHSecurityGroup.GroupId]
        SubnetId: !Ref JenkinsSubnet
        Tags:
          - Key: "Name"
            Value: "Jenkins Server"
        UserData:                       
          Fn::Base64: !Sub |            
            #!/bin/bash -xe
            yum update -y
            yum install java-1.8.0 -y
            yum remove java-1.7.0-openjdk -y
            wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
            rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            yum install jenkins -y
            service jenkins start
            yum install git -y
            usermod -aG docker jenkins


#        BlockDeviceMappings:
##          -
##            DeviceName: "/dev/sda1"
##            Ebs:
##              VolumeSize: "50"
##          -
#          - DeviceName: "/dev/sdm"
#            Ebs:
#               VolumeType: "io1"
#               Iops: "200"
#               DeleteOnTermination: "false"
#               VolumeSize: "20"
#          - DeviceName: "/dev/sdk"
#            NoDevice: {}
   MyEIP:
      Type: "AWS::EC2::EIP"
      Properties:
        InstanceId: !Ref Ec2Instances

   SSHSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        VpcId: !Ref JenkinsVPC
        GroupDescription: "Enable SSH access via port 22"
        SecurityGroupIngress:
            -
              CidrIp: "0.0.0.0/0"
              FromPort: "22"
              IpProtocol: "tcp"
              ToPort: "22"
            -
              CidrIp: "0.0.0.0/0"
              FromPort: "8080"
              IpProtocol: -1
              ToPort: "8080"

   JenkinsVPC:
      Type: "AWS::EC2::VPC"
      Properties:
        CidrBlock: "10.0.0.0/16"
        Tags:
           - Key: "Name"
             Value: "Jenkin's VPC"

   JenkinsSubnet:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: !Ref JenkinsVPC
        AvailabilityZone: "us-east-1a"
        CidrBlock: "10.0.1.0/24"
        MapPublicIpOnLaunch: true
        Tags:
           - Key: "Name"
             Value: "Jenkin's Subnet"

   InternetGateway:
      Type: "AWS::EC2::InternetGateway"
      DependsOn: JenkinsVPC
      Properties:
        Tags:
          - Key: "Name"
            Value: "Jenkins IgW"

   InternetGatewayAttachment:
      Type: "AWS::EC2::VPCGatewayAttachment"
      DependsOn: InternetGateway
      Properties:
         InternetGatewayId: !Ref InternetGateway
         VpcId: !Ref JenkinsVPC


   JenkinsRouteTable:
      Type: "AWS::EC2::RouteTable"
      Properties:
         VpcId: !Ref JenkinsVPC
         Tags:
            - Key: "Name"
              Value: "Jenkins Route Table"

   DefaultPublicRoute:
      Type: "AWS::EC2::Route"
      DependsOn: InternetGatewayAttachment
      Properties:
         RouteTableId: !Ref JenkinsRouteTable
         DestinationCidrBlock: "0.0.0.0/0"
         GatewayId: !Ref InternetGateway

   PublicSubnet1RouteTableAssociation:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
         RouteTableId: !Ref JenkinsRouteTable
         SubnetId: !Ref JenkinsSubnet
